### ISSUE TITLE
Please provide documentation on how to verify firmware and bootloader

### ISSUE THREAD

**Issue by Giszmo** [OneKeyHQ/firmware#17]
https://onekey.so/en-US/hardware claims the firmware and bootloader are Open Source yet nowhere in the (English) documentation can I find how to verify or at least obtain the firmware binary. Furthermore the [linked repository](https://github.com/OneKeyHQ/OneKey-Wallet) is just a text document, not mentioning "firmware", so I'm not even sure this repo is correct for this issue.

For the purpose of [WalletScrutiny's review of your wallet](https://walletscrutiny.com/hardware/onekey/) I will have to conclude the hardware wallet uses closed source due to the missing link from the product's page to this or any other repository containing firmware source code.

Please update your product website to

- [ ] link to the correct firmware and bootloader repositories
- [ ] link to the signed binaries for every release
- [ ] document how the hardware wallet asks the user for approval, at least optionally **showing the binary's hash**, so the user can make sure he's installing what he wants to install

As this repository here is a fork of Trezor's firmware, I assume this is merely a documentation issue and hope to soon be able to feature your product as reproducible just like the [Trezor One](https://walletscrutiny.com/hardware/trezorOne/).

**Comment by kedoubitcoin** [comment]
All our code is open source, you can compile and generate your own binaries, and we will add HASH values in future versions.

**Comment by thomasplus** [comment]
@kedoubitcoin 

I cloned the project, then installed the dependencies per the Trezor instructions, and I can execute `poetry run./script/setup && poetry run./script/cibuild` without issue, however I believe this builds the Trezor One firmware, not the OneKey Mini firmware, correct? I get a lot of issues when I run `ONEKEY MINI=1 poetry run./script/setup && ONEKEY MINI=1 poetry run./script/cibuild`, can you tell me how to build the firmware for the OneKey Mini?

ERROR:
```
menu_para.c: In function ‘menu_para_brightness’:
menu_para.c:55:10: error: ‘brightnessLow’ undeclared (first use in this function)
   55 |     case brightnessLow:
      |          ^~~~~~~~~~~~~
menu_para.c:55:10: note: each undeclared identifier is reported only once for each function it appears in
menu_para.c:57:10: error: ‘brightnessMedium’ undeclared (first use in this function)
   57 |     case brightnessMedium:
      |          ^~~~~~~~~~~~~~~~
menu_para.c:59:10: error: ‘brightnessHigh’ undeclared (first use in this function)
   59 |     case brightnessHigh:
      |          ^~~~~~~~~~~~~~
menu_para.c: In function ‘menu_para_set_brightness’:
menu_para.c:100:24: error: ‘brightnessHigh’ undeclared (first use in this function)
  100 |   uint32_t value[3] = {brightnessHigh, brightnessMedium, brightnessLow};
      |                        ^~~~~~~~~~~~~~
menu_para.c:100:40: error: ‘brightnessMedium’ undeclared (first use in this function)
  100 |   uint32_t value[3] = {brightnessHigh, brightnessMedium, brightnessLow};
      |                                        ^~~~~~~~~~~~~~~~
menu_para.c:100:58: error: ‘brightnessLow’ undeclared (first use in this function)
  100 |   uint32_t value[3] = {brightnessHigh, brightnessMedium, brightnessLow};
```

**Comment by adrelanos** [comment]
https://github.com/OneKeyHQ/firmware/issues/404 @Giszmo
