### ISSUE TITLE
Cannot sign into any site using OneKey Hardware Wallet & Metamask. Lack of Trezor v9 support.

### ISSUE THREAD

**Issue by robwilkes** [OneKeyHQ/firmware#466]
**Describe the bug**
Can't log into any website, basically, can't use my OneKey Touch (with Metamask).
Trying to sign in to any site, with Metamask, "https://connect.trezor.io/9/popup.html" pops up momentarily then closes.
Reported to support 4 weeks ago, was acknowledged as a known issue with Metamask now using Trezor v9 SDK, however I haven't seen any activity here regarding it so I'm now reporting it so it can be tracked properly.

**Firmware version and revision**
SafeOS 4.3.0 & OneKey App 4.9.0

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: MetaMask 10.34.3
 - OS: macOS
 - Browser: Brave & Chrome
 - Version: Brave 1.56.14 & Chrome 115.0.5790.170

**To Reproduce**
1. Import hardware wallet to MetaMask
2. Go to opensea.io
3. Connect wallet / go to settings
4. Attempt to sign in

**Expected behavior**
Hardware wallet should ask you to sign data (it doesn't)

**Screenshots**
N/A

**Additional context**
It works with OneKey browser extension (you can sign in), but I have a lot of wallets in MetaMask, and switching between MetaMask and OneKey for different wallets/sites, is convoluted.

**Comment by revan-zhang** [comment]
Hi @robwilkes. Thanks for your report. We have notice this issue.It will be fixed at next release.(classic/mini v3.3.0, touch v4.5.0)

**Comment by robwilkes** [comment]
@loatheb if you have a branch you're making the changes in I am happy to test it

**Comment by robwilkes** [comment]
working, thanks
