### ISSUE TITLE
Can't send transaction to new EVM network from Metamask

### ISSUE THREAD

**Issue by TkzcM** [OneKeyHQ/firmware#471]
**Describe the bug**
After 4.5.0 firmware update, I can't send transaction on Base/Kava EVM/Linea etc. The device could only sign transaction on mainnet/bsc/avax and "already supported" chains. Any new EVM chain won't work after 4.5.0 firmware update.

**Firmware version and revision**
OneKey Touch 4.5.0

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: MetaMask
 - OS: macOS
 - Browser: Chrome
 - Version: 10.34.5

**To Reproduce**
1. Add "Base Network" on https://chainlist.org
2. Send any transaction
3. <img width="409" alt="截屏2023-08-24 13 55 27" src="https://github.com/OneKeyHQ/firmware/assets/45264418/5f93290e-17d5-45ce-8d33-f76d00c5a5ef">

**Expected behavior**
Device show "签署 EVM 交易" and send transaction successfully.

**Screenshots**
Above.

**Additional context**
None

**Comment by revan-zhang** [comment]
Thanks for your report, we have noticed this problem and are ready to release Touch v4.5.1 to fix this problem.https://github.com/OneKeyHQ/firmware/pull/470

The reason of the problem is that we do not handle these configurations without chainId inside properly, thanks again for your report.

**Comment by revan-zhang** [comment]
Hi @TkzcM 
Thanks again for your report.We have released v4.5.1 for OneKey Touch last week. https://github.com/OneKeyHQ/firmware/releases/tag/touch%2Fv4.5.1

**Comment by TkzcM** [comment]
@loatheb When will the firmware become available at in-app update?
As install firmware from file will wipe the device.
