### ISSUE TITLE
"Verifing" message after entering the pin

### ISSUE THREAD

**Issue by drumm2k** [OneKeyHQ/firmware#561]
After entering the pin on OneKey Classic 1S there is a message "Verifing" instead of "Verif**y**ing" (english language).

This triggers me every time. Couldn't find any translations in this repo so couldn't create pull request with the fix. Maybe contributors or OneKeyHQ members could fix this.

**Comment by revan-zhang** [comment]
Sorry for the late reply, this problem has been fixed in the latest version.
